# Generated by Django 3.2.11 on 2022-01-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='Location',
        ),
    ]
