# Generated by Django 3.2.11 on 2022-01-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20220125_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='montant',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='loc_statut',
            field=models.CharField(blank=True, choices=[('En cours', 'En cours'), ('Annulé', 'Annulé'), ('Terminé', 'Terminé')], default='En cours', max_length=30, null=True),
        ),
    ]
