# Generated by Django 3.2.11 on 2022-01-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_alter_location_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='montant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
