# Generated by Django 3.2.11 on 2022-01-26 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_alter_location_montant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='montant',
        ),
    ]
