# Generated by Django 3.2.11 on 2022-01-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_remove_location_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='montant',
            field=models.IntegerField(default=200, null=True),
        ),
    ]
