# Generated by Django 4.0 on 2021-12-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
                ('cli_num', models.IntegerField(db_column='CLI_NUM')),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cli_id', models.AutoField(db_column='CLI_ID', primary_key=True, serialize=False)),
                ('cli_nom', models.CharField(blank=True, db_column='CLI_NOM', max_length=100, null=True)),
                ('cli_prenom', models.CharField(blank=True, db_column='CLI_PRENOM', max_length=100, null=True)),
                ('cli_adresseposte', models.CharField(blank=True, db_column='CLI_ADRESSEPOSTE', max_length=100, null=True)),
                ('cli_date_naissance', models.IntegerField(blank=True, db_column='CLI_DATE_NAISSANCE', null=True)),
                ('cli_mail', models.CharField(blank=True, db_column='CLI_MAIL', max_length=100, null=True)),
                ('cli_tel', models.CharField(blank=True, db_column='CLI_TEl', max_length=100, null=True)),
                ('cli_membre', models.CharField(blank=True, db_column='CLI_MEMBRE', max_length=100, null=True)),
                ('cli_date_debut', models.DateField()),
                ('cli_date_fin', models.DateField()),
                ('cli_num', models.IntegerField(db_column='CLI_NUM')),
            ],
            options={
                'db_table': 'Client',
                'managed': False,
            },
        ),
    ]
