# Generated by Django 4.0 on 2021-12-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cli_id', models.AutoField(db_column='CLI_ID', primary_key=True, serialize=False)),
                ('cli_nom', models.CharField(blank=True, db_column='CLI_NOM', max_length=100, null=True)),
                ('cli_prenom', models.CharField(blank=True, db_column='CLI_PRENOM', max_length=100, null=True)),
                ('cli_adresseposte', models.CharField(blank=True, db_column='CLI_ADRESSEPOSTE', max_length=100, null=True)),
                ('cli_date_naissance', models.DateField()),
                ('cli_mail', models.CharField(blank=True, db_column='CLI_MAIL', max_length=100, null=True)),
                ('cli_tel', models.CharField(blank=True, db_column='CLI_TEl', max_length=100, null=True)),
                ('cli_membre', models.CharField(blank=True, db_column='CLI_MEMBRE', max_length=100, null=True)),
                ('cli_date_debut', models.DateField()),
                ('cli_date_fin', models.DateField()),
                ('cli_num', models.IntegerField(db_column='CLI_NUM')),
            ],
            options={
                'db_table': 'Client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.AutoField(db_column='LOC_ID', primary_key=True, serialize=False)),
                ('loc_statut', models.CharField(blank=True, choices=[('En cours', 'En cours'), ('Annulé', 'Annulé'), ('Demande de diminution', 'Demande de diminution'), ('Demande de prolongation', 'Demande de prolongation'), ('En attente', 'En attente'), ('Terminé', 'Terminé')], db_column='LOC_STATUT', default='En cours', max_length=30, null=True)),
                ('loc_num', models.IntegerField(db_column='LOC_NUM')),
                ('date_modifier', models.DateField(blank=True)),
            ],
            options={
                'db_table': 'Location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location_Velo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('mail_envoyer', models.CharField(default='False', max_length=30)),
                ('loc_statut', models.CharField(blank=True, choices=[('En cours', 'En cours'), ('Annulé', 'Annulé'), ('Terminé', 'Terminé')], db_column='LOC_STATUT', default='En cours', max_length=30, null=True)),
                ('loc_num', models.IntegerField(db_column='LOC_NUM')),
            ],
            options={
                'db_table': 'Location_Velo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Velo',
            fields=[
                ('vel_id', models.AutoField(db_column='VEL_ID', primary_key=True, serialize=False)),
                ('vel_num_cadre', models.IntegerField(blank=True, db_column='VEL_NUM_CADRE', null=True)),
                ('vel_nom', models.TextField(blank=True, db_column='VEL_NOM', null=True)),
                ('vel_marque', models.TextField(blank=True, db_column='VEL_MARQUE', null=True)),
                ('vel_couleur', models.TextField(blank=True, db_column='VEL_COULEUR', null=True)),
                ('vel_type', models.TextField(blank=True, db_column='VEL_TYPE', null=True)),
                ('vel_photo', models.TextField(blank=True, db_column='VEL_PHOTO', null=True)),
                ('vel_statut', models.TextField(blank=True, db_column='VEL_STATUT', null=True)),
                ('vel_etat', models.TextField(blank=True, db_column='VEL_ETAT', null=True)),
                ('vel_remarque', models.TextField(blank=True, db_column='VEL_REMARQUE', null=True)),
                ('vel_num', models.IntegerField(blank=True, db_column='VEL_NUM')),
            ],
            options={
                'db_table': 'Velo',
                'managed': False,
            },
        ),
    ]
